substitutions:
  devicename: light_bulb_1
  friendly_name: light_bulb_1
  ip_address: !secret light_bulb_1

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_id
  password: !secret wifi_pwd
  manual_ip:
    static_ip: ${ip_address}
    gateway: !secret brama
    subnet: !secret maska

# Enable logging
logger:

# Enable Home Assistant API
api:


ota:

output:
  - platform: esp8266_pwm
    id: output_daylight
    pin: GPIO5
  - platform: esp8266_pwm
    id: output_warm_white
    pin: GPIO12
    
light:
  - platform: cwww
    name: "Light Bulb"
    id: light_bulb_1
    cold_white: output_daylight
    warm_white: output_warm_white
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 2700 K

    # Ensure the light turns on by default if the physical switch is actuated.
    restore_mode: ALWAYS_ON
    
